version: '3'

networks:
  golang:

services:
  go:
    build:
      context: .
      dockerfile: go.dockerfile
    container_name: gocontainer
    ports:
      - 4000:4000
    networks:
      - golang
  mongo:
    image: mongo
    container_name: mongohost
    restart: unless-stopped
    ports:
      - 27017:27017
    volumes:
      - ./mongo_storage:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root
    networks:
      - golang
  mongo-express:
    image: mongo-express
    restart: always
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: root
      ME_CONFIG_BASICAUTH_USERNAME: admin
      ME_CONFIG_BASICAUTH_PASSWORD: admin123#
      ME_CONFIG_MONGODB_URL: mongodb://root:root@mongo:27017/
    networks:
      - golang